baseURL = "https://www.swayerealty.com/"
languageCode = "en-us"
summaryLength = 25
enableRobotsTXT = "true"
[markup.goldmark.renderer]
unsafe= true
[outputs]
home = ["HTML", "RSS", "JSON"]
[taxonomies]
category = "categories"
cities = "cities"
featured = "featured"
properties = "properties"
states = "states"
status = "status"
tag = "tags"
zip-code = "zip-codes"